config/routes.rb
Rails.application.routes.draw do
  resources :theses
  resources :contracts
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root to: "home#index"

  get "/introduction", to: "home#introduction", as: :introduction
  get "/service", to: "home#service", as: :service
  get "/tariffs", to: "home#tariffs", as: :tariffs
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contract.rb
class Contract < ApplicationRecord
end

app/models/tesis.rb
class Tesis < ApplicationRecord
end

app/models/thesis.rb
class Thesis < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/contracts_controller.rb
class ContractsController < ApplicationController
  before_action :set_contract, only: [:show, :edit, :update, :destroy]

  # GET /contracts
  # GET /contracts.json
  def index
    @contracts = Contract.all
  end

  # GET /contracts/1
  # GET /contracts/1.json
  def show
  end

  # GET /contracts/new
  def new
    @contract = Contract.new
  end

  # GET /contracts/1/edit
  def edit
  end

  # POST /contracts
  # POST /contracts.json
  def create
    @contract = Contract.new(contract_params)

    respond_to do |format|
      if @contract.save
        format.html { redirect_to @contract, notice: 'Contract was successfully created.' }
        format.json { render :show, status: :created, location: @contract }
      else
        format.html { render :new }
        format.json { render json: @contract.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contracts/1
  # PATCH/PUT /contracts/1.json
  def update
    respond_to do |format|
      if @contract.update(contract_params)
        format.html { redirect_to @contract, notice: 'Contract was successfully updated.' }
        format.json { render :show, status: :ok, location: @contract }
      else
        format.html { render :edit }
        format.json { render json: @contract.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contracts/1
  # DELETE /contracts/1.json
  def destroy
    @contract.destroy
    respond_to do |format|
      format.html { redirect_to contracts_url, notice: 'Contract was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contract
      @contract = Contract.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def contract_params
      params.require(:contract).permit(:place, :date, :name, :dpi, :age, :civil_status, :email, :phone, :service, :career, :academic_grade, :mount, :fee, :way_to_pay, :contract_service, :social)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    def index
    end

    def introduction
      #code
    end

    def service
      #code
    end

    def tariffs
      #code
    end
end

app/controllers/theses_controller.rb
class ThesesController < ApplicationController
  before_action :set_thesis, only: [:show, :edit, :update, :destroy]

  # GET /theses
  # GET /theses.json
  def index
    @theses = Thesis.all
  end

  # GET /theses/1
  # GET /theses/1.json
  def show
  end

  # GET /theses/new
  def new
    @thesis = Thesis.new
  end

  # GET /theses/1/edit
  def edit
  end

  # POST /theses
  # POST /theses.json
  def create
    @thesis = Thesis.new(thesis_params)

    respond_to do |format|
      if @thesis.save
        format.html { redirect_to @thesis, notice: 'Thesis was successfully created.' }
        format.json { render :show, status: :created, location: @thesis }
      else
        format.html { render :new }
        format.json { render json: @thesis.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /theses/1
  # PATCH/PUT /theses/1.json
  def update
    respond_to do |format|
      if @thesis.update(thesis_params)
        format.html { redirect_to @thesis, notice: 'Thesis was successfully updated.' }
        format.json { render :show, status: :ok, location: @thesis }
      else
        format.html { render :edit }
        format.json { render json: @thesis.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /theses/1
  # DELETE /theses/1.json
  def destroy
    @thesis.destroy
    respond_to do |format|
      format.html { redirect_to theses_url, notice: 'Thesis was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_thesis
      @thesis = Thesis.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def thesis_params
      params.require(:thesis).permit(:name, :phone, :email, :career, :grade, :university, :delivery_time, :type_document, :body)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contracts_helper.rb
module ContractsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/theses_helper.rb
module ThesesHelper
end

app/views/contracts/_form.html.erb
<%= form_with(model: contract, local: true) do |form| %>
  <% if contract.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(contract.errors.count, "error") %> prohibited this contract from being saved:</h2>

      <ul>
        <% contract.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mdl-textfield mdl-js-textfield full-width">
    <%= form.text_field :place, class:"mdl-textfield__input" %>
    <%= form.label 'Lugar',  class:"mdl-textfield__label" %>
  </div>

  <div class="mdl-textfield mdl-js-textfield full-width">
    <%= form.date_select :date, class:"mdl-textfield__input" %>
    <%= form.label 'Fecha',  class:"mdl-textfield__label" %>
  </div>

  <div class="mdl-textfield mdl-js-textfield full-width">
    <%= form.text_field :name, class:"mdl-textfield__input" %>
    <%= form.label 'Nombre',  class:"mdl-textfield__label" %>
  </div>

  <div class="mdl-textfield mdl-js-textfield full-width">
    <%= form.text_field :dpi, class:"mdl-textfield__input" %>
    <%= form.label 'Numero de documento de identificacion personal',  class:"mdl-textfield__label" %>
  </div>

  <div class="mdl-textfield mdl-js-textfield full-width">
    <%= form.number_field :age, class:"mdl-textfield__input" %>
    <%= form.label 'Edad',  class:"mdl-textfield__label" %>
  </div>

  <div class="mdl-textfield mdl-js-textfield full-width">
    <%= form.text_field :civil_status, class:"mdl-textfield__input" %>
    <%= form.label 'Estado Civil',  class:"mdl-textfield__label" %>
  </div>

  <div class="mdl-textfield mdl-js-textfield full-width">
    <%= form.text_field :email, class:"mdl-textfield__input" %>
    <%= form.label 'Correo Electronico',  class:"mdl-textfield__label" %>
  </div>

  <div class="mdl-textfield mdl-js-textfield full-width">
    <%= form.number_field :phone, class:"mdl-textfield__input" %>
    <%= form.label 'Telefono',  class:"mdl-textfield__label" %>
  </div>

  <div class="mdl-textfield mdl-js-textfield full-width">
    <%= form.text_field :service, class:"mdl-textfield__input" %>
    <%= form.label 'Servicio que contratara',  class:"mdl-textfield__label" %>
  </div>

  <div class="mdl-textfield mdl-js-textfield full-width">
    <%= form.text_field :career, class:"mdl-textfield__input" %>
    <%= form.label 'Carrera',  class:"mdl-textfield__label" %>
  </div>

  <div class="mdl-textfield mdl-js-textfield full-width">
    <%= form.text_field :academic_grade, class:"mdl-textfield__input" %>
    <%= form.label 'Grado academico de la tesis',  class:"mdl-textfield__label" %>
  </div>

  <div class="mdl-textfield mdl-js-textfield full-width">
    <%= form.number_field :mount, class:"mdl-textfield__input" %>
    <%= form.label 'Monto total a pagar',  class:"mdl-textfield__label" %>
  </div>

  <div class="mdl-textfield mdl-js-textfield full-width">
    <%= form.number_field :fee, class:"mdl-textfield__input" %>
    <%= form.label 'Pagos en que fraccionará el monto total',  class:"mdl-textfield__label" %>
  </div>

  <div class="mdl-textfield mdl-js-textfield full-width">
    <%= form.text_field :way_to_pay, class:"mdl-textfield__input" %>
    <%= form.label 'Forma de pago',  class:"mdl-textfield__label" %>
  </div>

  <div class="mdl-textfield mdl-js-textfield full-width">
    <%= form.text_field :contract_service, class:"mdl-textfield__input" %>
    <%= form.label 'Tipo de servicio',  class:"mdl-textfield__label" %>
  </div>

  <div class="mdl-textfield mdl-js-textfield full-width">
    <%= form.text_field :social, class:"mdl-textfield__input" %>
    <%= form.label 'Forma en la que se entero de nosotros',  class:"mdl-textfield__label" %>
  </div>

  <div class="actions margin-top text-right">
    <%= link_to 'cancelar', tariffs_path, class:'mdl-button mdl-js-button mdl-button--primary margin-right' %>
    <%= form.submit 'Enviar', class:'mdl-button mdl-js-button mdl-button--raised black white-text'%>
  </div>
<% end %>

app/views/contracts/edit.html.erb
<h1>Editing Contract</h1>

<%= render 'form', contract: @contract %>

<%= link_to 'Show', @contract %> |
<%= link_to 'Back', contracts_path %>

app/views/contracts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Contracts</h1>

<table>
  <thead>
    <tr>
      <th>Place</th>
      <th>Date</th>
      <th>Name</th>
      <th>Dpi</th>
      <th>Age</th>
      <th>Civil status</th>
      <th>Email</th>
      <th>Phone</th>
      <th>Service</th>
      <th>Career</th>
      <th>Academic grade</th>
      <th>Mount</th>
      <th>Fee</th>
      <th>Way to pay</th>
      <th>Contract service</th>
      <th>Social</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @contracts.each do |contract| %>
      <tr>
        <td><%= contract.place %></td>
        <td><%= contract.date %></td>
        <td><%= contract.name %></td>
        <td><%= contract.dpi %></td>
        <td><%= contract.age %></td>
        <td><%= contract.civil_status %></td>
        <td><%= contract.email %></td>
        <td><%= contract.phone %></td>
        <td><%= contract.service %></td>
        <td><%= contract.career %></td>
        <td><%= contract.academic_grade %></td>
        <td><%= contract.mount %></td>
        <td><%= contract.fee %></td>
        <td><%= contract.way_to_pay %></td>
        <td><%= contract.contract_service %></td>
        <td><%= contract.social %></td>
        <td><%= link_to 'Show', contract %></td>
        <td><%= link_to 'Edit', edit_contract_path(contract) %></td>
        <td><%= link_to 'Destroy', contract, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Contract', new_contract_path %>

app/views/contracts/new.html.erb
<div class="black white-text no-margin full-width center-xs">
    <h1 class="white-text no-margin">Contrato para Guatemala</h1>
    <p class="white-text">Por favor llene los siguientes datos para los datos del contrato</p>
</div>
<div class="row center-xs middle-xs full-height">
    <div class="col-xs-12 col-sm-8">
        <div class="box">
            <%= render 'form', contract: @contract %>
        </div>
    </div>
</div>

app/views/contracts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Place:</strong>
  <%= @contract.place %>
</p>

<p>
  <strong>Date:</strong>
  <%= @contract.date %>
</p>

<p>
  <strong>Name:</strong>
  <%= @contract.name %>
</p>

<p>
  <strong>Dpi:</strong>
  <%= @contract.dpi %>
</p>

<p>
  <strong>Age:</strong>
  <%= @contract.age %>
</p>

<p>
  <strong>Civil status:</strong>
  <%= @contract.civil_status %>
</p>

<p>
  <strong>Email:</strong>
  <%= @contract.email %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @contract.phone %>
</p>

<p>
  <strong>Service:</strong>
  <%= @contract.service %>
</p>

<p>
  <strong>Career:</strong>
  <%= @contract.career %>
</p>

<p>
  <strong>Academic grade:</strong>
  <%= @contract.academic_grade %>
</p>

<p>
  <strong>Mount:</strong>
  <%= @contract.mount %>
</p>

<p>
  <strong>Fee:</strong>
  <%= @contract.fee %>
</p>

<p>
  <strong>Way to pay:</strong>
  <%= @contract.way_to_pay %>
</p>

<p>
  <strong>Contract service:</strong>
  <%= @contract.contract_service %>
</p>

<p>
  <strong>Social:</strong>
  <%= @contract.social %>
</p>

<%= link_to 'Edit', edit_contract_path(@contract) %> |
<%= link_to 'Back', contracts_path %>

app/views/home/index.html.erb
<div class="row center-xs middle-xs full-height">
    <div class="col-xs-12 col-sm-6">
        <div class="box">
            <div class="big-padding black white-text">
                <h1>Bienvenido a Utesis</h1>
                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad</p>
                <%= link_to 'Estudiante', introduction_path, class: 'mdl-button mdl-js-button mdl-button--raised mdl-button--accent'%>
                <%= link_to 'Profesional', root_path, class: 'mdl-button mdl-js-button mdl-button--raised white black-text btn-disabled'%>
            </div>
        </div>
    </div>
</div>

app/views/home/introduction.html.erb
<div class="row center-xs middle-xs full-height">
    <div class="col-xs-12 col-sm-6">
        <div class="box">
            <h1>Video</h1>
            <%= link_to 'Siguiente', service_path, class: 'mdl-button mdl-js-button mdl-button--raised mdl-button--accent' %>
        </div>
    </div>
</div>

app/views/home/service.html.erb
<div class="row center-xs middle-xs full-height">
    <div class="col-xs-12 col-sm-6">
        <div class="box">
            <div class="big-padding black">
                <h1 class="white-text">Qué tipo de servicio necesita?</h1>
                <div class="row">
                    <div class="col-xs-12 col-sm-6">
                        <div class="box">
                            <div class="mdl-card mdl-shadow--2dp">
                                <div class="mdl-card__title">
                                    <h2 class="mdl-card__title-text">A. Servicio Básico:</h2>
                                </div>
                                <div class="mdl-card__supporting-text">
                                    <ul class="demo-list-icon mdl-list">
                                      <li class="mdl-list__item">
                                        <span class="mdl-list__item-primary-content">
                                            <i class="material-icons mdl-list__item-icon">assignment_turned_in</i>
                                            Colaboración en propuesta de temas (gratis)
                                        </span>
                                      </li>
                                      <li class="mdl-list__item">
                                        <span class="mdl-list__item-primary-content">
                                            <i class="material-icons mdl-list__item-icon">assignment_turned_in</i>
                                            Colaboración en desarrollo de Plan, protocolo o anteproyecto (gratis)
                                        </span>
                                      </li>
                                      <li class="mdl-list__item">
                                        <span class="mdl-list__item-primary-content">
                                            <i class="material-icons mdl-list__item-icon">assignment_turned_in</i>
                                            Tesis o equivalente
                                        </span>
                                      </li>
                                      <li class="mdl-list__item">
                                        <span class="mdl-list__item-primary-content">
                                            <i class="material-icons mdl-list__item-icon">assignment_turned_in</i>
                                            Correcciones de FONDO (ilimitadas) en todas las etapas.
                                        </span>
                                      </li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-xs-12 col-sm-6">
                        <div class="box">
                            <div class="mdl-card mdl-shadow--2dp">
                                <div class="mdl-card__title">
                                    <h2 class="mdl-card__title-text">B. Servicio Completo:</h2>
                                </div>
                                <div class="mdl-card__supporting-text">
                                    <ul class="demo-list-icon mdl-list">
                                      <li class="mdl-list__item">
                                        <span class="mdl-list__item-primary-content">
                                            <i class="material-icons mdl-list__item-icon">assignment_turned_in</i>
                                            Colaboración en propuesta de Tema (gratis)
                                        </span>
                                      </li>
                                      <li class="mdl-list__item">
                                        <span class="mdl-list__item-primary-content">
                                            <i class="material-icons mdl-list__item-icon">assignment_turned_in</i>
                                            Colaboración en desarrollo de Plan, protocolo o anteproyecto (gratis)
                                        </span>
                                      </li>
                                      <li class="mdl-list__item">
                                        <span class="mdl-list__item-primary-content">
                                            <i class="material-icons mdl-list__item-icon">assignment_turned_in</i>
                                            Tesis o equivalente
                                        </span>
                                      </li>
                                      <li class="mdl-list__item">
                                        <span class="mdl-list__item-primary-content">
                                            <i class="material-icons mdl-list__item-icon">assignment_turned_in</i>
                                            Correcciones de FONDO (ilimitadas) en todas las etapas
                                        </span>
                                      </li>
                                      <li class="mdl-list__item">
                                        <span class="mdl-list__item-primary-content">
                                            <i class="material-icons mdl-list__item-icon">assignment_turned_in</i>
                                            Correcciones de FORMA (ilimitadas) en todas las etapas
                                        </span>
                                      </li>
                                      <li class="mdl-list__item">
                                        <span class="mdl-list__item-primary-content">
                                            <i class="material-icons mdl-list__item-icon">assignment_turned_in</i>
                                            Acompañamiento y asesoría profesional (de forma remota)
                                        </span>
                                      </li>
                                      <li class="mdl-list__item">
                                        <span class="mdl-list__item-primary-content">
                                            <i class="material-icons mdl-list__item-icon">assignment_turned_in</i>
                                            Participación del departamento de Edición (es decir, adecuación del trabajo a manuales de forma en específico)
                                        </span>
                                      </li>
                                      <li class="mdl-list__item">
                                        <span class="mdl-list__item-primary-content">
                                            <i class="material-icons mdl-list__item-icon">assignment_turned_in</i>
                                            Participación del departamento de Filología o lingüistica.
                                        </span>
                                      </li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="margin-top">
                    <%= link_to "Tengo Avances", new_thesis_path,  class:'mdl-button mdl-js-button mdl-button--raised white'%>
                    <%= link_to "Siguiente", tariffs_path, class:'mdl-button mdl-js-button mdl-button--raised mdl-button--accent'%>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/home/tariffs.html.erb
<div class="row center-xs middle-xs full-height">
    <div class="col-xs-12 col-sm-6">
        <div class="box">
            <div class="big-padding black">
                <h1 class="white-text">Tarifas</h1>
                <div class="row">
                    <div class="col-xs-12 col-sm-6">
                        <div class="box">
                            <div class="mdl-card mdl-shadow--2dp">
                                <div class="mdl-card__title">
                                    <h2 class="mdl-card__title-text">A. Servicio Básico:</h2>
                                </div>
                                <div class="mdl-card__title">
                                    <h2 class="mdl-card__title-text">Q7,485</h2>
                                </div>
                                <div class="mdl-card__title">
                                    <p class="mdl-card__subtitle-text">(pagos durante 3 meses, o sea el monto dividio en 3, con tarjeta de crédito odébito, o 12 visacuotas) </p>
                                </div>
                                <div class="mdl-card__title">
                                    <h2 class="mdl-card__title-text">Q6,485 </h2>
                                </div>
                                <div class="mdl-card__title">
                                    <p class="mdl-card__subtitle-text">pago de contado, es decir, en efectivo.</p>
                                </div>
                                <div class="mdl-card__supporting-text">
                                    <ul class="demo-list-icon mdl-list">
                                      <li class="mdl-list__item">
                                        <span class="mdl-list__item-primary-content">
                                            <i class="material-icons mdl-list__item-icon">assignment_turned_in</i>
                                            Colaboración en propuesta de temas (gratis)
                                        </span>
                                      </li>
                                      <li class="mdl-list__item">
                                        <span class="mdl-list__item-primary-content">
                                            <i class="material-icons mdl-list__item-icon">assignment_turned_in</i>
                                            Colaboración en desarrollo de Plan, protocolo o anteproyecto (gratis)
                                        </span>
                                      </li>
                                      <li class="mdl-list__item">
                                        <span class="mdl-list__item-primary-content">
                                            <i class="material-icons mdl-list__item-icon">assignment_turned_in</i>
                                            Tesis o equivalente
                                        </span>
                                      </li>
                                      <li class="mdl-list__item">
                                        <span class="mdl-list__item-primary-content">
                                            <i class="material-icons mdl-list__item-icon">assignment_turned_in</i>
                                            Correcciones de FONDO (ilimitadas) en todas las 3 etapas.
                                        </span>
                                      </li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-xs-12 col-sm-6">
                        <div class="box">
                            <div class="mdl-card mdl-shadow--2dp">
                                <div class="mdl-card__title">
                                    <h2 class="mdl-card__title-text">B. Servicio Completo:</h2>
                                </div>
                                <div class="mdl-card__title">
                                    <h2 class="mdl-card__title-text">Q8,485</h2>
                                </div>
                                <div class="mdl-card__title">
                                    <p class="mdl-card__subtitle-text">(pagos durante 3 meses, o sea el monto dividio en 3, con tarjeta de crédito odébito, o 12 visacuotas) </p>
                                </div>
                                <div class="mdl-card__title">
                                    <h2 class="mdl-card__title-text">Q7,485</h2>
                                </div>
                                <div class="mdl-card__title">
                                    <p class="mdl-card__subtitle-text">pago de contado, es decir, en efectivo.</p>
                                </div>
                                <div class="mdl-card__supporting-text">
                                    <ul class="demo-list-icon mdl-list">
                                      <li class="mdl-list__item">
                                        <span class="mdl-list__item-primary-content">
                                            <i class="material-icons mdl-list__item-icon">assignment_turned_in</i>
                                            Colaboración en propuesta de Tema (gratis)
                                        </span>
                                      </li>
                                      <li class="mdl-list__item">
                                        <span class="mdl-list__item-primary-content">
                                            <i class="material-icons mdl-list__item-icon">assignment_turned_in</i>
                                            Colaboración en desarrollo de Plan, protocolo o anteproyecto (gratis)
                                        </span>
                                      </li>
                                      <li class="mdl-list__item">
                                        <span class="mdl-list__item-primary-content">
                                            <i class="material-icons mdl-list__item-icon">assignment_turned_in</i>
                                            Tesis o equivalente
                                        </span>
                                      </li>
                                      <li class="mdl-list__item">
                                        <span class="mdl-list__item-primary-content">
                                            <i class="material-icons mdl-list__item-icon">assignment_turned_in</i>
                                            Correcciones de FONDO (ilimitadas) en todas las etapas
                                        </span>
                                      </li>
                                      <li class="mdl-list__item">
                                        <span class="mdl-list__item-primary-content">
                                            <i class="material-icons mdl-list__item-icon">assignment_turned_in</i>
                                            Correcciones de FORMA (ilimitadas) en todas las etapas
                                        </span>
                                      </li>
                                      <li class="mdl-list__item">
                                        <span class="mdl-list__item-primary-content">
                                            <i class="material-icons mdl-list__item-icon">assignment_turned_in</i>
                                            Acompañamiento y asesoría profesional (de forma remota)
                                        </span>
                                      </li>
                                      <li class="mdl-list__item">
                                        <span class="mdl-list__item-primary-content">
                                            <i class="material-icons mdl-list__item-icon">assignment_turned_in</i>
                                            Participación del departamento de Edición (es decir, adecuación del trabajo a manuales de forma en específico)
                                        </span>
                                      </li>
                                      <li class="mdl-list__item">
                                        <span class="mdl-list__item-primary-content">
                                            <i class="material-icons mdl-list__item-icon">assignment_turned_in</i>
                                            Participación del departamento de Filología o lingüistica.
                                        </span>
                                      </li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="margin-top">
                    <%= link_to "Siguiente", new_contract_path, class:'mdl-button mdl-js-button mdl-button--raised mdl-button--accent'%>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/theses/edit.html.erb
<h1>Editing Thesis</h1>

<%= render 'form', thesis: @thesis %>

<%= link_to 'Show', @thesis %> |
<%= link_to 'Back', theses_path %>

app/views/theses/new.html.erb
<div class="black white-text no-margin full-width center-xs">
    <h1 class="white-text no-margin">Avances de Tesis</h1>
    <p class="white-text">Por favor llene los siguientes datos para su cotización y envíe el mismo con la documentación que considere necesaria.</p>
</div>
<div class="row center-xs middle-xs full-height">
    <div class="col-xs-12 col-sm-8">
        <div class="box">
            <%= render 'form', thesis: @thesis %>
        </div>
    </div>
</div>

app/views/theses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @thesis.name %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @thesis.phone %>
</p>

<p>
  <strong>Email:</strong>
  <%= @thesis.email %>
</p>

<p>
  <strong>Career:</strong>
  <%= @thesis.career %>
</p>

<p>
  <strong>Grade:</strong>
  <%= @thesis.grade %>
</p>

<p>
  <strong>University:</strong>
  <%= @thesis.university %>
</p>

<p>
  <strong>Delivery time:</strong>
  <%= @thesis.delivery_time %>
</p>

<p>
  <strong>Type document:</strong>
  <%= @thesis.type_document %>
</p>

<p>
  <strong>Body:</strong>
  <%= @thesis.body %>
</p>

<%= link_to 'Edit', edit_thesis_path(@thesis) %> |
<%= link_to 'Back', theses_path %>